
name: Node.js CI

on:
  push:
    branches:  
    - master
    - releases/*
    - initial_commit-react
  pull_request:
    branches:
    - master
    - releases/*
    - initial_commit-react

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: git config --global user.email "aakashkh13@gmail.com"
    - run: git config --global user.name "Aakash Khanna"
    - run: git remote remove origin
    - run: rm -rf .git
    - name: See where we are
      run: |
        pwd
        cd build/
        git init
        git add .
        git commit -m "Automated push"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        repository: aakashkhanna/aakashkhanna.github.io
        directory: build
       env:
        CI: true

