
name: Node.js CI

on:
  push:
    branches:  
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm Build
      run: |
        npm ci
        npm run build --if-present
    - name: Remove source git repo
      run: |
        git remote remove origin
        rm -rf .git
    - name: Commit Build Artifacts to gh page repo
      run: |
        git config --global user.email "aakashkh13@gmail.com"
        git config --global user.name "Aakash Khanna"
        cd build/
        git init
        git add .
        git commit -m "Automated push"
    - name: Push changes to gh page repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        repository: aakashkhanna/aakashkhanna.github.io
        directory: build
        force: true
     
